TYPE: POTPVP
GAME_MODIFIERS:
  ENABLED: FALSE
ENDERPEARL_COOLDOWN:
  ENABLED: TRUE
  DURATION: 16000
REDIS:
  HOST: localhost
STATE:
  LOBBY:
    COUNTDOWN: 35000
  EVENT:
    FIRST_REFILL:
      START: 0
      COUNTDOWN: 300000
    SECOND_REFILL:
      START: 450000
      COUNTDOWN: 180000
    DEATHMATCH:
      START: 900000
      COUNTDOWN: 180000
      PERIOD: 5000