GAME_MODIFIERS:
  ENABLED: FALSE
ENDERPEARL_COOLDOWN:
  ENABLED: TRUE
  DURATION: 16000
REDIS:
  HOST: localhost
MONGO:
  HOST: localhost
  PORT: 27017
  DATABASE: "skywars"
  AUTHENTICATION:
    ENABLED: FALSE
    USER: user
    PASSWORD: password
STATE:
  LOBBY:
    COUNTDOWN: 35000
  EVENT:
    FIRST_REFILL:
      START: 0
      COUNTDOWN: 300000
    SECOND_REFILL:
      START: 450000
      COUNTDOWN: 180000
    DEATHMATCH:
      START: 900000
      COUNTDOWN: 180000
      PERIOD: 5000